export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const LIST_PRODUCT = 'LIST_PRODUCT'
export const LIST_PRODUCT_OK = 'LIST_PRODUCT_OK'
export const LIST_PRODUCT_ERROR = 'LIST_PRODUCT_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_OK = 'EDIT_PRODUCT_OK'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'
